#!/bin/bash

name="${1:-bot}"
norestartfile="$name.norestart"

echo $name
echo $norestartfile

while true; do
	if [ -f  $norestartfile ]; then
		rm $norestartfile
	fi

	python3 -u bot.py $name >> log 2>&1 &
	pid=$!
	echo $pid
	echo \[$(date +"%F %T")\]\[\"$name\"\] Started PCBot \[PID=$pid\] >> log

	wait $pid
	echo \[$(date +"%F %T")\]\[\"$name\"\] PCBot was terminated! >> log

	if [ -f $norestartfile ]; then
		echo \[$(date +"%F %T")\]\[\"$name\"\] File $norestartfile found, exiting restart loop >> log
		break
	fi

	echo \[$(date +"%F %T")\]\[\"$name\"\] Restarting >> log
done
